version: '3.8'

services:
  backup-service:
    image: alpine
    volumes:
      - ./:/ue5project
      - ./backups:/backups
    command: ["/bin/sh", "-c", "while true; do /ue5project/backup-script.sh; sleep 86400; done"]